### ISSUE TITLE
API-Request to retrieve a label.

### ISSUE THREAD

**Issue by azngeek** [netresearch/dhl-module-carrier-paket-returns#1]
We are implementing Magento by mainly using the API. Is it possible, to use the API only to generate a label? If yes, how could we do this? Endpoint, Request-Parameter etc. I was not able to finde an API-Documentation.

**Comment by mam08ixo** [comment]
DHL offers an API to create shipment return labels, yes. The [README of the API SDK](https://github.com/netresearch/dhl-sdk-api-bcs-returns/blob/2.0.0/README.md#features) that we use includes a link to the API documentation in the DHL developer portal. You will need to register a developer account to access it. Hope that helps.
